name: apkmonitoring
description: "Aplikasi Monitoring Work Order PLTU Pacitan"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Charts
  cupertino_icons: ^1.0.8
  fl_chart: ^0.64.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.5

  # File & Data Management
  file_picker: ^10.2.0
  open_file: ^3.3.2
  excel: ^2.1.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  http: ^1.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
